all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: sasl_ssl
preflight:
  hosts:
    hadoop-fra-2.intern.beon.net:
    hadoop-fra-4.intern.beon.net:
    hadoop-fra-5.intern.beon.net:
ssl_CA:
  hosts:
    hadoop-fra-4.intern.beon.net:
zookeeper:
  hosts:
    hadoop-fra-4.intern.beon.net:
broker:
  hosts:
    hadoop-fra-2.intern.beon.net:
      kafka:
        broker:
          id: 1
    hadoop-fra-4.intern.beon.net:
      kafka:
        broker:
          id: 2
    hadoop-fra-5.intern.beon.net:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    hadoop-fra-4.intern.beon.net:
control-center:
  hosts:
    hadoop-fra-2.intern.beon.net:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: hadoop-fra-4.intern.beon.net::8083
connect-distributed:
  hosts:
    hadoop-fra-4.intern.beon.net:
kafka-rest:
  hosts:
    hadoop-fra-4.intern.beon.net:
ksql:
  hosts:
    hadoop-fra-4.intern.beon.net:
